import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './providers'
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Biswajeet Behera',
    template: '%s | Biswajeet Behera'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Providers >
          {children}
        </Providers>
        <Analytics />
      </body>
    </html>

  )
}
